### ISSUE TITLE
[US] As a user, I want to see the home page by typing the URL

### ISSUE THREAD

**Issue by taliacodes** [gh-blue-barracudas/grace-shopper#1]
Sub-tasks:
- [x] Display nav component - issue #19 
- [x] Display footer component - issue #19
- [x] Display header and hero image - issue #20
