### ISSUE TITLE
[US] As a user, I want to be able to browse all products by clicking the All Products tab

### ISSUE THREAD

**Issue by ahsunkim** [gh-blue-barracudas/grace-shopper#3]
- [x] Write a products model - issue #29 
- [x] Write a route to serve up all products - issue #32 
- [x] Make a React component that displays all products once clicking on the All Products category page - issue #35
- [x] Write a subreducer for products - issue #38
