### ISSUE TITLE
[US] As a user, I want to be able to look at one product by clicking the product link/image

### ISSUE THREAD

**Issue by ahsunkim** [gh-blue-barracudas/grace-shopper#4]
- [x] Write a route to serve up a single product (based on its id), _including that product’s Category information
- [x] Add to product sub-reducer to manage a selected product in your Redux store #38 
- [x] Write a component to display a single product #45 
- [x] The Nav and Footer should be present on the Single Product Page #19
