### ISSUE TITLE
[US] As a user, I want to be able to add a product to cart by clicking the add-to-cart button on the product page

### ISSUE THREAD

**Issue by ahsunkim** [gh-blue-barracudas/grace-shopper#5]
- [x] Create a Cart Model #46

- [x] Create a Cart sub-reducer #43 

- [x] Add an ‘Add To Cart’ button on the page with the functionality to add a product to the current cart.  #34
