### ISSUE TITLE
[US] As a user, I want to see a styled site

### ISSUE THREAD

**Issue by ahsunkim** [gh-blue-barracudas/grace-shopper#68]
- [x] Style Homepage - issue #69 
- [x] Style All Products Category Page - issue #70 
- [x] Style Single Product Display Page - issue #71 
- [x] Style Login and Sign Up Pages - issue #72 
- [x] Style Cart Page - issue #73 
- [ ] Style Shipping and Billing Page - issue #74 
- [x] Style Order Confirmation Page - issue #75
