### ISSUE TITLE
[US] As a guest user, I want to be able to sign in by clicking sign-in on Nav

### ISSUE THREAD

**Issue by ahsunkim** [gh-blue-barracudas/grace-shopper#7]
- [x] Write a route to find the existing user - issue #26
- [x] After log-in, go back to the home page - issue #27
- [x] Maintain the user on session - issue #31
